#!/usr/bin/env python3
"""Generate wood species database JSON. Compact: species defined as tuples, expanded via templates."""
import json, re, random

random.seed(42)

# (common, scientific, category, janka, density_lbft3, grain, color_desc, color_hex,
#  workability, durability, tangential_shrink%, radial_shrink%, price_low_bf, price_high_bf,
#  origin, sustainability, primary_uses)
S = [
    # NORTH AMERICAN HARDWOODS
    ("Red Oak","Quercus rubra","hardwood",1290,44,"straight","Pinkish-red to reddish-brown","#B5651D",4,2,8.6,4.4,3.0,8.0,"Eastern North America","abundant","furniture|flooring|cabinets|veneer"),
    ("White Oak","Quercus alba","hardwood",1360,47,"straight","Light brown with olive tint","#C4A35A",4,4,10.5,5.6,3.5,10.0,"Eastern North America","abundant","furniture|flooring|boat building|barrels|outdoor furniture"),
    ("Hard Maple","Acer saccharum","hardwood",1450,44,"straight to wavy","Creamy white to light reddish-brown","#F2E0C9",3,2,9.9,4.8,4.0,10.0,"Northeastern North America","abundant","flooring|furniture|cutting boards|bowling alleys|musical instruments"),
    ("Soft Maple","Acer rubrum","hardwood",950,38,"straight","Light reddish-brown","#D4B896",4,2,8.2,4.0,2.5,6.0,"Eastern North America","abundant","furniture|cabinets|veneer|turning"),
    ("Black Walnut","Juglans nigra","hardwood",1010,38,"straight to wavy","Rich dark chocolate brown","#3B2314",4,3,7.8,5.5,6.0,14.0,"Eastern North America","moderate","furniture|gunstocks|veneer|cabinets|turning"),
    ("Black Cherry","Prunus serotina","hardwood",950,35,"straight","Reddish-brown, darkens with age","#8B4513",4,2,7.1,3.7,4.0,10.0,"Eastern North America","abundant","furniture|cabinets|veneer|musical instruments|turning"),
    ("White Ash","Fraxinus americana","hardwood",1320,42,"straight","Light tan to medium brown","#C9B78E",4,2,7.8,4.9,2.5,7.0,"Eastern North America","threatened","tool handles|baseball bats|furniture|flooring"),
    ("Yellow Birch","Betula alleghaniensis","hardwood",1260,43,"straight to wavy","Light reddish-brown","#D4A76A",3,2,9.2,7.3,3.0,7.0,"Northeastern North America","abundant","furniture|cabinets|flooring|veneer|plywood"),
    ("American Beech","Fagus grandifolia","hardwood",1300,45,"straight","Pale cream to pinkish-brown","#E8D5B7",3,1,11.9,5.5,2.0,5.0,"Eastern North America","abundant","furniture|flooring|turning|food containers|tool handles"),
    ("Hickory","Carya ovata","hardwood",1820,51,"straight","Light to medium brown","#C4A672",3,2,10.5,7.0,3.0,7.0,"Eastern North America","abundant","tool handles|flooring|smoking meat|ladder rungs|sporting goods"),
    ("Pecan","Carya illinoinensis","hardwood",1820,46,"straight","Light to reddish-brown","#B8956A",3,2,8.9,4.9,3.0,7.0,"Southern North America","abundant","flooring|furniture|veneer|smoking meat"),
    ("American Elm","Ulmus americana","hardwood",830,35,"interlocked","Light to medium brown","#C4A87C",3,2,9.5,4.2,2.0,5.0,"Eastern North America","threatened","furniture|boxes|baskets|hockey sticks"),
    ("Cottonwood","Populus deltoides","hardwood",430,28,"straight to interlocked","Light yellowish-white","#E8DCC8",4,1,9.2,3.9,1.5,3.5,"North America","abundant","pallets|crates|paper pulp|boxes"),
    ("Basswood","Tilia americana","hardwood",410,26,"straight","Pale white to light brown","#EDE4D0",5,1,9.3,6.6,2.0,5.0,"Eastern North America","abundant","carving|turning|veneer|blinds|musical instruments"),
    ("Yellow Poplar","Liriodendron tulipifera","hardwood",540,29,"straight","Yellowish-green to brown","#C4B87C",5,2,8.2,4.6,2.0,5.0,"Eastern North America","abundant","cabinets|furniture|siding|pallets|plywood"),
    ("Sweetgum","Liquidambar styraciflua","hardwood",850,36,"interlocked","Reddish-brown with darker streaks","#9E6B4A",3,2,10.2,5.3,2.0,5.0,"Southeastern North America","abundant","veneer|plywood|furniture|boxes"),
    ("Sycamore","Platanus occidentalis","hardwood",770,35,"interlocked","Light tan with distinctive fleck","#D4C4A0",3,1,8.4,5.0,2.0,5.0,"Eastern North America","abundant","furniture|veneer|butcher blocks|boxes"),
    ("Hackberry","Celtis occidentalis","hardwood",880,37,"straight","Yellowish-gray to light brown","#C8B896",4,1,8.9,4.8,1.5,4.0,"Eastern North America","abundant","furniture|veneer|boxes|turning"),
    ("Osage Orange","Maclura pomifera","hardwood",2620,54,"straight to interlocked","Bright golden-yellow to dark brown","#D4A017",2,5,5.2,3.2,3.0,8.0,"Central North America","abundant","fence posts|bows|turning|tool handles"),
    ("Black Locust","Robinia pseudoacacia","hardwood",1700,48,"straight","Yellowish-green to dark brown","#8B7D3C",3,5,7.2,4.6,3.0,8.0,"Eastern North America","abundant","fence posts|boat building|flooring|outdoor furniture"),
    ("Sassafras","Sassafras albidum","hardwood",630,31,"straight","Golden to dark brown","#B8860B",4,3,6.2,4.0,3.0,7.0,"Eastern North America","moderate","furniture|boat building|fencing|cooperage"),
    ("Butternut","Juglans cinerea","hardwood",490,27,"straight","Light tan to golden brown","#C8A96E",5,2,6.4,3.4,4.0,10.0,"Eastern North America","threatened","carving|furniture|veneer|boxes"),
    ("Catalpa","Catalpa speciosa","hardwood",580,29,"straight","Grayish-brown","#A09078",4,3,4.9,2.5,2.0,5.0,"Central North America","moderate","fence posts|furniture|carving"),
    ("Honey Locust","Gleditsia triacanthos","hardwood",1580,45,"straight to interlocked","Reddish-brown","#8B5E3C",3,3,6.6,4.2,3.0,7.0,"Eastern North America","abundant","fence posts|furniture|turning|pallets"),
    ("Kentucky Coffeetree","Gymnocladus dioicus","hardwood",1390,43,"straight","Light reddish-brown","#A0785A",3,3,6.7,3.9,4.0,10.0,"Central North America","moderate","furniture|fence posts|cabinets"),
    ("Persimmon","Diospyros virginiana","hardwood",2300,52,"straight","Creamy white sapwood, dark heartwood","#F5E6CC",2,3,11.2,7.9,5.0,15.0,"Southeastern North America","moderate","golf club heads|textile shuttles|turning|billiard cues"),
    ("Tupelo","Nyssa sylvatica","hardwood",810,35,"interlocked","Pale grayish-brown","#C0B098",3,1,8.7,5.1,2.0,5.0,"Eastern North America","abundant","furniture|veneer|pallets|carving"),
    ("Alder","Alnus rubra","hardwood",590,28,"straight","Light tan to reddish-brown","#C89870",5,1,7.3,4.4,2.5,5.5,"Pacific Northwest","abundant","furniture|cabinets|turning|carving"),
    ("Madrone","Arbutus menziesii","hardwood",1460,45,"interlocked","Pinkish-red to reddish-brown","#B85C48",2,2,12.4,5.4,4.0,10.0,"Pacific Coast","moderate","turning|furniture|veneer|flooring"),
    ("Oregon Myrtle","Umbellularia californica","hardwood",1360,39,"straight to wavy","Golden to olive-brown with darker streaks","#8B7340",3,3,8.1,4.5,6.0,16.0,"Pacific Coast","moderate","turning|veneer|furniture|gunstocks"),
    ("Tanoak","Notholithocarpus densiflorus","hardwood",1510,42,"interlocked","Reddish-brown","#A07050",3,2,11.7,5.8,2.0,5.0,"Pacific Coast","moderate","furniture|flooring|firewood"),
    ("Chinkapin","Chrysolepis chrysophylla","hardwood",1120,36,"straight","Light reddish-brown","#B89070",3,2,7.4,3.6,3.0,7.0,"Pacific Coast","moderate","furniture|veneer|posts"),
    ("Mesquite","Prosopis spp.","hardwood",2345,52,"interlocked","Dark reddish-brown","#5C3317",2,5,4.8,3.2,5.0,15.0,"Southwestern North America","abundant","furniture|flooring|turning|BBQ smoking"),

    # TROPICAL HARDWOODS
    ("Teak","Tectona grandis","hardwood",1070,41,"straight","Golden to medium brown","#C49A6C",4,5,5.8,2.6,12.0,30.0,"Southeast Asia","plantation-grown","boat building|outdoor furniture|flooring|veneer|decking"),
    ("Mahogany","Swietenia macrophylla","hardwood",900,35,"straight to interlocked","Reddish-brown, darkens over time","#8B4726",5,4,5.1,3.3,8.0,20.0,"Central/South America","vulnerable","furniture|cabinets|veneer|boat building|musical instruments"),
    ("African Mahogany","Khaya ivorensis","hardwood",830,35,"interlocked","Pinkish to reddish-brown","#A0522D",4,3,6.4,4.2,5.0,12.0,"West Africa","vulnerable","furniture|veneer|boat building|cabinets"),
    ("Sapele","Entandrophragma cylindricum","hardwood",1410,42,"interlocked","Reddish-brown with ribbon figure","#8B5A2B",3,3,7.4,4.6,5.0,12.0,"West Africa","vulnerable","furniture|veneer|flooring|musical instruments|boat building"),
    ("Ipe","Tabebuia spp.","hardwood",3510,69,"straight to interlocked","Olive-brown to dark brown","#5C4033",1,5,6.6,5.9,8.0,25.0,"Central/South America","moderate","decking|flooring|outdoor furniture|heavy construction"),
    ("Purpleheart","Peltogyne purpurea","hardwood",2520,56,"straight","Vivid violet-purple","#7B3F8E",2,4,6.1,3.2,6.0,14.0,"Central/South America","moderate","furniture accents|flooring|turning|inlays|jewelry"),
    ("Padauk","Pterocarpus soyauxii","hardwood",2170,47,"straight to interlocked","Vivid orange-red, darkens to brown","#D44500",3,4,5.2,3.3,6.0,14.0,"West/Central Africa","moderate","furniture|flooring|turning|musical instruments"),
    ("Bubinga","Guibourtia demeusei","hardwood",2410,56,"straight to interlocked","Pinkish-red to dark reddish-brown","#993333",3,3,7.8,5.8,8.0,20.0,"West Africa","threatened","furniture|veneer|turning|musical instruments|inlays"),
    ("Wenge","Millettia laurentii","hardwood",1930,55,"straight","Very dark brown to black","#3C1414",2,3,8.8,5.9,7.0,18.0,"Central Africa","threatened","furniture|flooring|veneer|paneling|musical instruments"),
    ("Zebrawood","Microberlinia brazzavillensis","hardwood",1830,50,"interlocked","Light gold with dark brown streaks","#C8A84E",3,3,8.0,5.4,7.0,16.0,"West Africa","vulnerable","veneer|furniture|turning|decorative objects"),
    ("Bocote","Cordia gerascanthus","hardwood",2010,52,"straight to interlocked","Golden-brown with dark lines","#A67C52",3,3,7.5,4.5,10.0,25.0,"Mexico/Central America","moderate","furniture|turning|musical instruments|knife handles"),
    ("Cocobolo","Dalbergia retusa","hardwood",2960,69,"straight to interlocked","Orange to deep red with black lines","#B03F2E",2,5,4.2,2.8,20.0,60.0,"Central America","vulnerable","turning|knife handles|musical instruments|inlays|jewelry"),
    ("Brazilian Rosewood","Dalbergia nigra","hardwood",2790,53,"straight to interlocked","Dark chocolate with black streaks","#3B1E08",2,4,4.6,2.9,50.0,200.0,"Brazil","critically endangered","musical instruments|fine furniture|veneer"),
    ("East Indian Rosewood","Dalbergia latifolia","hardwood",2440,52,"interlocked","Dark purple-brown with dark streaks","#4A2040",3,4,5.8,2.9,15.0,40.0,"India/Southeast Asia","vulnerable","furniture|musical instruments|veneer|turning"),
    ("Ebony","Diospyros ebenum","hardwood",3220,72,"straight","Jet black","#1A1110",2,5,8.8,5.3,30.0,100.0,"Sri Lanka/India","critically endangered","musical instruments|inlays|turning|piano keys|knife handles"),
    ("Macassar Ebony","Diospyros celebica","hardwood",3220,70,"straight","Black with brown/gold streaks","#2C1A0E",2,5,8.2,4.6,25.0,80.0,"Southeast Asia","vulnerable","furniture|veneer|musical instruments|inlays"),
    ("Bloodwood","Brosimum rubescens","hardwood",2900,62,"straight","Vivid bright red","#CC0000",2,4,6.6,3.5,8.0,20.0,"South America","moderate","turning|inlays|accents|jewelry|musical instruments"),
    ("Lignum Vitae","Guaiacum officinale","hardwood",4500,80,"interlocked","Dark olive to greenish-brown","#556B2F",1,5,5.2,3.0,40.0,120.0,"Caribbean/Northern South America","endangered","bearings|mallet heads|turning|marine hardware"),
    ("Jatoba","Hymenaea courbaril","hardwood",2350,57,"interlocked","Salmon-red to orangish-brown","#B86840",2,4,8.5,4.5,5.0,12.0,"Central/South America","moderate","flooring|furniture|turning|tool handles"),
    ("Cumaru","Dipteryx odorata","hardwood",3330,68,"interlocked","Medium to dark brown","#7B5B3A",1,5,8.1,5.4,5.0,12.0,"South America","moderate","decking|flooring|heavy construction"),
    ("Tigerwood","Astronium graveolens","hardwood",1850,55,"straight to interlocked","Orange-brown with dark streaks","#C87830",3,3,7.6,5.2,5.0,12.0,"Central/South America","moderate","flooring|furniture|veneer|decking"),
    ("Lacewood","Panopsis spp.","hardwood",840,34,"interlocked","Pinkish-brown with lace pattern","#C8A080",4,2,8.8,3.8,5.0,12.0,"South America","moderate","veneer|furniture|decorative objects|turning"),
    ("Leopardwood","Roupala brasiliensis","hardwood",2150,50,"interlocked","Reddish-brown with dark flecks","#A0603C",3,3,10.0,5.4,8.0,20.0,"South America","moderate","veneer|furniture|turning|decorative objects"),
    ("Kingwood","Dalbergia cearensis","hardwood",3340,75,"straight","Dark violet-brown with black streaks","#4A1A5E",2,4,5.4,3.1,30.0,80.0,"Brazil","vulnerable","turning|inlays|musical instruments|fine furniture"),
    ("Tulipwood","Dalbergia decipularis","hardwood",2500,60,"interlocked","Pink to salmon with yellow streaks","#E8787A",2,3,6.4,4.2,25.0,70.0,"Brazil","vulnerable","inlays|turning|jewelry boxes|musical instruments"),
    ("Ziricote","Cordia dodecandra","hardwood",2070,51,"straight to interlocked","Dark brown with black spider-web lines","#3B2820",3,3,7.2,3.9,15.0,35.0,"Mexico/Central America","moderate","furniture|guitar backs|turning|veneer"),
    ("Gonçalo Alves","Astronium fraxinifolium","hardwood",2160,58,"interlocked","Reddish-brown with dark streaks","#A05030",2,4,7.6,5.0,5.0,12.0,"South America","moderate","flooring|furniture|turning|knife handles"),
    ("Marblewood","Zygia racemosa","hardwood",2180,56,"straight","Golden-tan with dark brown swirls","#C8A040",2,3,8.9,5.2,7.0,16.0,"South America","moderate","veneer|furniture|turning|inlays"),
    ("Yellowheart","Euxylophora paraensis","hardwood",1790,50,"straight","Bright vivid yellow","#FFD700",3,3,6.8,4.2,6.0,14.0,"South America","moderate","inlays|turning|flooring|furniture accents"),
    ("Massaranduba","Manilkara bidentata","hardwood",3190,68,"straight","Dark reddish-brown","#6E2A1E",1,5,9.2,6.2,4.0,10.0,"South America","moderate","decking|heavy construction|flooring"),
    ("Garapa","Apuleia leiocarpa","hardwood",1210,50,"interlocked","Light golden-yellow","#D4B050",3,3,7.0,4.4,4.0,10.0,"South America","moderate","decking|flooring|outdoor furniture"),
    ("Cambara","Erisma uncinatum","hardwood",780,35,"interlocked","Light pinkish-brown","#C8A088",4,3,7.2,4.0,3.0,7.0,"South America","moderate","siding|decking|general construction"),
    ("Mora","Mora excelsa","hardwood",2460,62,"interlocked","Deep reddish-brown","#6B2E14","2",4,8.5,5.8,4.0,10.0,"South America","moderate","marine construction|heavy timber|flooring"),
    ("Angelique","Dicorynia guianensis","hardwood",1290,46,"interlocked","Pinkish to reddish-brown","#A86848",3,4,8.8,5.2,4.0,10.0,"South America","moderate","marine construction|bridge building|decking"),
    ("Tatajuba","Bagassa guianensis","hardwood",1570,50,"interlocked","Golden-yellow to russet-brown","#C89840",3,5,5.4,3.1,4.0,9.0,"South America","moderate","decking|flooring|construction"),
    ("Courbaril","Hymenaea courbaril","hardwood",2350,57,"interlocked","Salmon-red to orangish-brown","#B86840",2,4,8.5,4.5,5.0,12.0,"Central/South America","moderate","flooring|furniture|heavy construction"),

    # AFRICAN HARDWOODS
    ("Iroko","Milicia excelsa","hardwood",1260,41,"interlocked","Yellow to golden-brown","#B8860B",4,5,5.4,2.8,5.0,12.0,"West Africa","vulnerable","outdoor furniture|boat building|flooring|veneer"),
    ("Utile","Entandrophragma utile","hardwood",1200,41,"interlocked","Pinkish to reddish-brown","#9E6B55",4,3,7.0,4.8,5.0,11.0,"West Africa","vulnerable","boat building|furniture|veneer|joinery"),
    ("African Blackwood","Dalbergia melanoxylon","hardwood",3670,79,"straight","Dark purplish-black","#1C1014",1,5,5.8,2.9,30.0,100.0,"East Africa","near threatened","musical instruments|turning|carving|inlays"),
    ("Movingui","Distemonanthus benthamianus","hardwood",1200,41,"interlocked","Bright yellow","#E8C840",3,3,6.0,3.5,4.0,9.0,"West Africa","moderate","flooring|furniture|boat building"),
    ("Okoume","Aucoumea klaineana","hardwood",380,27,"interlocked","Pinkish-brown","#D4A088",5,1,7.2,4.1,2.0,5.0,"Central Africa","vulnerable","plywood|veneer|boat building|light construction"),
    ("Limba","Terminalia superba","hardwood",490,32,"straight to interlocked","Pale yellowish to light brown","#D8C890",4,1,6.0,3.8,3.0,7.0,"West Africa","moderate","veneer|plywood|furniture|musical instruments"),
    ("Obeche","Triplochiton scleroxylon","hardwood",350,24,"interlocked","Pale yellow to whitish","#EDE0C0",5,1,5.4,3.0,2.0,5.0,"West Africa","moderate","model building|carving|plywood|furniture interiors"),
    ("Muhuhu","Brachylaena huillensis","hardwood",2300,62,"interlocked","Yellowish to dark brown","#8B7340",2,5,6.2,3.5,6.0,14.0,"East Africa","near threatened","flooring|carving|turning"),
    ("Ovangkol","Guibourtia ehie","hardwood",1630,48,"interlocked","Yellowish-brown with dark streaks","#8B7240",3,3,7.6,4.5,5.0,12.0,"West Africa","vulnerable","musical instruments|furniture|veneer"),
    ("Moabi","Baillonella toxisperma","hardwood",1490,48,"straight","Pinkish to reddish-brown","#A06848",3,4,8.0,4.8,5.0,12.0,"West Africa","vulnerable","furniture|flooring|boat building|veneer"),
    ("Niangon","Heritiera utilis","hardwood",1080,37,"interlocked","Pinkish to reddish-brown","#B07860",4,3,7.4,4.0,4.0,9.0,"West Africa","vulnerable","joinery|furniture|boat building"),
    ("Sipo","Entandrophragma utile","hardwood",1200,40,"interlocked","Reddish-brown","#9E5B40",4,3,7.6,5.0,5.0,11.0,"West Africa","vulnerable","furniture|veneer|joinery|boat building"),
    ("Afrormosia","Pericopsis elata","hardwood",1560,43,"interlocked","Yellowish to golden-brown","#B08830",3,5,6.0,3.0,8.0,18.0,"West Africa","endangered","furniture|flooring|boat building|outdoor"),
    ("Abachi","Triplochiton scleroxylon","hardwood",350,24,"interlocked","Pale yellow to cream","#EDE0B8",5,1,5.4,3.0,2.0,5.0,"West Africa","moderate","sauna benches|model building|plywood"),
    ("Ekki","Lophira alata","hardwood",3220,67,"interlocked","Dark reddish-brown","#5C2820",1,5,10.0,7.8,5.0,12.0,"West Africa","vulnerable","marine construction|heavy timber|bridge building"),
    ("Doussie","Afzelia africana","hardwood",1810,50,"interlocked","Reddish-brown","#8B4030",3,5,4.6,2.8,6.0,14.0,"West Africa","vulnerable","flooring|furniture|outdoor construction"),

    # EUROPEAN HARDWOODS
    ("European Oak","Quercus robur","hardwood",1120,43,"straight","Light tan to golden-brown","#C8A860",4,4,8.8,4.3,4.0,12.0,"Europe","abundant","furniture|flooring|boat building|barrels|timber framing"),
    ("European Beech","Fagus sylvatica","hardwood",1300,44,"straight","Pale cream to pinkish-brown","#E0CBB0",4,1,11.8,5.8,3.0,7.0,"Europe","abundant","furniture|flooring|turning|tool handles|plywood"),
    ("European Walnut","Juglans regia","hardwood",1010,37,"straight to wavy","Medium to dark brown with gray streaks","#5C4030",4,3,6.4,4.3,8.0,20.0,"Europe/West Asia","moderate","furniture|veneer|gunstocks|turning|cabinets"),
    ("European Ash","Fraxinus excelsior","hardwood",1320,42,"straight","Light tan to pale brown","#D0B888",4,2,8.0,5.0,3.0,7.0,"Europe","threatened","tool handles|furniture|flooring|sporting goods"),
    ("Olive","Olea europaea","hardwood",2700,62,"interlocked","Cream with dark brown streaks","#808040",2,4,8.5,5.5,10.0,25.0,"Mediterranean","moderate","turning|carving|decorative objects|utensils"),
    ("European Cherry","Prunus avium","hardwood",1150,38,"straight","Pinkish to reddish-brown","#9E6048",4,2,7.0,3.5,5.0,12.0,"Europe","abundant","furniture|cabinets|veneer|turning"),
    ("European Elm","Ulmus procera","hardwood",860,36,"interlocked","Light to medium brown","#B89870",3,2,8.6,4.2,3.0,7.0,"Europe","threatened","furniture|chairs|coffins|boat building"),
    ("Sycamore Maple","Acer pseudoplatanus","hardwood",1050,39,"straight to wavy","Creamy white","#F0E8D0",4,1,8.4,3.8,4.0,10.0,"Europe","abundant","veneer|musical instruments|furniture|kitchenware"),
    ("European Linden","Tilia europaea","hardwood",410,26,"straight","Creamy white to pale yellow","#F0E8C8",5,1,9.5,6.8,3.0,7.0,"Europe","abundant","carving|model building|veneer|blinds"),
    ("Holly","Ilex aquifolium","hardwood",1020,40,"interlocked","Ivory white","#FFFFF0",3,1,9.8,4.8,6.0,15.0,"Europe","moderate","inlays|turning|chess pieces|engraving blocks"),
    ("Boxwood","Buxus sempervirens","hardwood",2840,62,"straight","Bright pale yellow","#EDE088",2,2,9.0,5.5,15.0,50.0,"Europe/West Asia","moderate","carving|engraving blocks|chess pieces|musical instruments|rulers"),
    ("Hornbeam","Carpinus betulus","hardwood",1630,47,"interlocked","Creamy white","#EEE8D0",2,1,11.0,6.8,3.0,7.0,"Europe","abundant","tool handles|chopping blocks|piano actions|flooring"),
    ("London Plane","Platanus × acerifolia","hardwood",1050,39,"interlocked","Light tan with lacewood figure","#D0B890",3,1,8.2,4.5,3.0,7.0,"Europe","abundant","veneer|furniture|turning|decorative work"),
    ("Swiss Pear","Pyrus communis","hardwood",1660,44,"straight","Pinkish-brown to salmon","#C89078",3,1,8.4,4.0,5.0,12.0,"Europe","moderate","carving|rulers|drawing instruments|musical instruments"),
    ("Yew","Taxus baccata","softwood",1520,43,"straight to wavy","Orange-red to purplish-brown","#A04828",3,4,4.0,2.6,10.0,30.0,"Europe","moderate","bows|turning|furniture|veneer|carving"),

    # ASIAN/OCEANIAN
    ("Merbau","Intsia bijuga","hardwood",1925,54,"interlocked","Orange-brown to dark red-brown","#8B3E2F",2,4,5.2,3.0,5.0,12.0,"Southeast Asia/Oceania","vulnerable","flooring|decking|furniture|boat building"),
    ("Jarrah","Eucalyptus marginata","hardwood",1910,51,"interlocked","Rich reddish-brown","#8B3626",2,4,8.6,3.8,5.0,12.0,"Western Australia","moderate","furniture|flooring|outdoor construction|turning"),
    ("Karri","