#!/usr/bin/env python3
"""Generate wood_species.json with 210 real wood species."""
import json, uuid, os

# (name, sci, cat[H/S], janka, density, grain, hex, workability, durability, price, region, uses)
# First 50 = free tier
DATA = [
("White Oak","Quercus alba","H",1360,.68,"Straight","#C4A35A",7,8,"$$","North America","Furniture, flooring, barrels"),
("Red Oak","Quercus rubra","H",1290,.63,"Straight","#B5651D",7,6,"$$","North America","Furniture, cabinetry, flooring"),
("Hard Maple","Acer saccharum","H",1450,.71,"Wavy","#E8D5B7",6,7,"$$$","North America","Flooring, cutting boards, furniture"),
("Black Walnut","Juglans nigra","H",1010,.55,"Wavy","#3B2314",8,7,"$$$","North America","Furniture, gunstocks, veneer"),
("Black Cherry","Prunus serotina","H",950,.50,"Straight","#8B4513",8,5,"$$$","North America","Furniture, cabinetry, instruments"),
("Eastern White Pine","Pinus strobus","S",380,.35,"Straight","#F5DEB3",9,3,"$","North America","Construction, trim, carving"),
("Douglas Fir","Pseudotsuga menziesii","S",660,.48,"Straight","#D2A679",7,6,"$","North America","Construction, plywood, framing"),
("Western Red Cedar","Thuja plicata","S",350,.32,"Straight","#A0522D",9,9,"$$","North America","Decking, siding, outdoor furniture"),
("Yellow Poplar","Liriodendron tulipifera","H",540,.42,"Straight","#C8B560",9,4,"$","North America","Painted furniture, trim, plywood"),
("White Ash","Fraxinus americana","H",1320,.60,"Straight","#D4C5A9",7,5,"$$","North America","Tool handles, bats, furniture"),
("Hickory","Carya spp.","H",1820,.72,"Straight","#C9A86C",5,7,"$$","North America","Tool handles, smoking, flooring"),
("Mahogany","Swietenia macrophylla","H",800,.49,"Interlocked","#6B3A2E",9,7,"$$$","Central America","Furniture, boats, instruments"),
("Teak","Tectona grandis","H",1070,.55,"Straight","#9C7A3C",6,10,"$$$$","Southeast Asia","Outdoor furniture, boats, flooring"),
("Sapele","Entandrophragma cylindricum","H",1410,.62,"Interlocked","#8B3A2F",6,7,"$$","Africa","Furniture, veneer, instruments"),
("IPE","Tabebuia spp.","H",3510,.96,"Interlocked","#4A3728",3,10,"$$$","South America","Decking, outdoor structures"),
("Southern Yellow Pine","Pinus palustris","S",870,.54,"Straight","#DAA06D",7,5,"$","North America","Construction, decking, plywood"),
("Yellow Birch","Betula alleghaniensis","H",1260,.62,"Wavy","#F0D9B5",7,4,"$$","North America","Plywood, cabinetry, furniture"),
("American Beech","Fagus grandifolia","H",1300,.64,"Straight","#E3C9A8",6,4,"$$","North America","Furniture, flooring, bending"),
("Red Alder","Alnus rubra","H",590,.41,"Straight","#C19A6B",8,3,"$","North America","Cabinetry, furniture, smoking"),
("Basswood","Tilia americana","H",410,.32,"Straight","#E8DCC8",10,2,"$","North America","Carving, blinds, models"),
("Redwood","Sequoia sempervirens","S",420,.35,"Straight","#A45A3D",8,8,"$$","North America","Decking, siding, outdoor"),
("Ebony","Diospyros ebenum","H",3080,.96,"Straight","#1C1C1C",4,9,"$$$$","Africa","Instruments, inlays, turning"),
("East Indian Rosewood","Dalbergia latifolia","H",2440,.80,"Interlocked","#5C3317",5,8,"$$$$","India","Instruments, furniture, veneer"),
("Purpleheart","Peltogyne purpurea","H",2520,.86,"Straight","#6B3FA0",5,8,"$$$","South America","Accents, flooring, furniture"),
("Padauk","Pterocarpus dalbergioides","H",2170,.77,"Interlocked","#D44500",6,8,"$$$","Africa","Flooring, turning, accents"),
("Zebrawood","Microberlinia brazzavillensis","H",1830,.71,"Interlocked","#C4A45A",5,6,"$$$","Africa","Veneer, furniture, accents"),
("Wenge","Millettia laurentii","H",1930,.80,"Straight","#3C2415",4,7,"$$$","Africa","Furniture, flooring, instruments"),
("Bocote","Cordia gerascanthus","H",2010,.75,"Interlocked","#A67B3D",5,7,"$$$","Mexico","Turning, inlays, handles"),
("Bloodwood","Brosimum rubescens","H",2900,.89,"Straight","#8B0000",4,8,"$$$","South America","Inlays, accents, turning"),
("Butternut","Juglans cinerea","H",490,.36,"Straight","#C4A35A",9,3,"$$","North America","Carving, furniture, paneling"),
("Eastern Red Cedar","Juniperus virginiana","S",900,.47,"Straight","#B5544A",7,9,"$$","North America","Closets, chests, fence posts"),
("Spruce","Picea spp.","S",510,.40,"Straight","#F5E6CC",8,3,"$","North America","Construction, soundboards"),
("Bald Cypress","Taxodium distichum","S",510,.46,"Straight","#C9A86C",8,8,"$$","North America","Outdoor, siding, boats"),
("Eastern Hemlock","Tsuga canadensis","S",500,.40,"Straight","#D6C4A8",7,3,"$","North America","Construction, framing"),
("Cottonwood","Populus deltoides","H",430,.35,"Interlocked","#E0D5C0",7,2,"$","North America","Pallets, crates"),
("American Elm","Ulmus americana","H",830,.50,"Interlocked","#B8956A",6,4,"$$","North America","Furniture, bending, chairs"),
("Sycamore","Platanus occidentalis","H",770,.49,"Interlocked","#DCC8A0",6,3,"$$","North America","Butcher blocks, furniture"),
("Pecan","Carya illinoinensis","H",1820,.66,"Straight","#B8860B",5,6,"$$","North America","Flooring, furniture, smoking"),
("Mesquite","Prosopis glandulosa","H",2345,.80,"Irregular","#6B3E26",4,8,"$$$","North America","Furniture, flooring, BBQ"),
("Western Larch","Larix occidentalis","S",830,.52,"Straight","#CC9966",6,6,"$$","North America","Outdoor, boats, decking"),
("Mango","Mangifera indica","H",1070,.52,"Interlocked","#A0724A",7,4,"$","Southeast Asia","Furniture, carving"),
("Jarrah","Eucalyptus marginata","H",1910,.82,"Interlocked","#8B3A28",5,8,"$$$","Australia","Flooring, outdoor, railway"),
("Bamboo","Phyllostachys edulis","H",1410,.65,"Straight","#E5D39E",6,6,"$$","Asia","Flooring, furniture, boards"),
("Balsa","Ochroma pyramidale","H",100,.12,"Straight","#FCF0D3",10,1,"$","South America","Models, insulation, surfboards"),
("Cocobolo","Dalbergia retusa","H",2960,.95,"Irregular","#B44322",4,9,"$$$$","Central America","Handles, instruments, turning"),
("Bubinga","Guibourtia demeusei","H",2410,.79,"Interlocked","#9C4230",5,7,"$$$$","Africa","Furniture, veneer, instruments"),
("Soft Maple","Acer rubrum","H",950,.54,"Wavy","#E0C8A0",8,5,"$$","North America","Furniture, cabinetry"),
("Black Locust","Robinia pseudoacacia","H",1700,.69,"Straight","#8B7D3C",5,10,"$$","North America","Fence posts, outdoor, tools"),
("Acacia","Acacia spp.","H",2300,.80,"Interlocked","#8B6914",5,8,"$$","Africa","Furniture, flooring, boards"),
("Koa","Acacia koa","H",1170,.55,"Interlocked","#9C6030",7,5,"$$$$","Hawaii","Instruments, furniture, veneer"),
("Yellowheart","Euxylophora paraensis","H",1790,.70,"Straight","#F0C420",6,6,"$$$","South America","Accents, inlays, turning"),
("Lacewood","Panopsis rubescens","H",840,.52,"Irregular","#C9A77C",6,4,"$$$","South America","Veneer, furniture, decor"),
("Canarywood","Centrolobium spp.","H",1520,.67,"Interlocked","#E8A040",6,5,"$$$","South America","Furniture, flooring, turning"),
("Katalox","Swartzia cubensis","H",3655,1.05,"Straight","#2C1608",3,10,"$$$","Central America","Flooring, turning, tools"),
("Ziricote","Cordia dodecandra","H",1680,.70,"Interlocked","#3B3024",5,7,"$$$$","Central America","Guitars, furniture, veneer"),
("Olivewood","Olea europaea","H",2700,.90,"Irregular","#9C8A60",4,7,"$$$","Mediterranean","Turning, utensils, decor"),
("Tulipwood","Dalbergia frutescens","H",1850,.96,"Interlocked","#D4728A",5,6,"$$$$","Brazil","Inlays, veneer, turning"),
("Lignum Vitae","Guaiacum officinale","H",4500,1.23,"Interlocked","#556B2F",2,10,"$$$$","Caribbean","Bearings, mallets, marine"),
("Kingwood","Dalbergia cearensis","H",3340,1.05,"Straight","#4A2040",4,8,"$$$$","Brazil","Inlays, turning, instruments"),
("Leopardwood","Roupala brasiliensis","H",2150,.76,"Irregular","#A0704A",5,5,"$$$","South America","Veneer, furniture, decor"),
("Osage Orange","Maclura pomifera","H",2620,.81,"Straight","#DAA520",4,10,"$$","North America","Fence posts, bows, turning"),
("Snakewood","Brosimum guianense","H",3800,1.10,"Irregular","#8B2500",3,8,"$$$$","South America","Inlays, bows, luxury"),
("African Blackwood","Dalbergia melanoxylon","H",3670,1.08,"Straight","#1A1110",3,9,"$$$$","Africa","Clarinets, oboes, turning"),
("Marblewood","Zygia racemosa","H",2270,.88,"Straight","#C4A060",4,6,"$$$","South America","Turning, furniture, accents"),
("Pink Ivory","Berchemia zeyheri","H",3230,.99,"Straight","#CC6680",4,7,"$$$$","Southern Africa","Turning, inlays, carving"),
("Jatoba","Hymenaea courbaril","H",2350,.89,"Interlocked","#A0522D",4,8,"$$$","South America","Flooring, furniture, tools"),
("Cumaru","Dipteryx odorata","H",3330,1.07,"Interlocked","#8B6C42",3,9,"$$$","South America","Decking, flooring, construction"),
("Iroko","Milicia excelsa","H",1260,.55,"Interlocked","#A08040",7,8,"$$","Africa","Outdoor, boats, flooring"),
("Afromosia","Pericopsis elata","H",1560,.62,"Interlocked","#8B7340",6,8,"$$$","Africa","Furniture, boats, flooring"),
("African Mahogany","Khaya ivorensis","H",830,.44,"Interlocked","#7C4030",8,6,"$$","Africa","Furniture, boats, cabinetry"),
("Spanish Cedar","Cedrela odorata","H",600,.40,"Straight","#A07050",9,7,"$$$","Central America","Cigar boxes, closets, boats"),
("Merbau","Intsia bijuga","H",1925,.74,"Interlocked","#7C3C28",5,8,"$$$","Southeast Asia","Decking, flooring, furniture"),
("Rubberwood","Hevea brasiliensis","H",960,.56,"Straight","#E0C890",7,3,"$","Southeast Asia","Furniture, toys, boards"),
("Paulownia","Paulownia tomentosa","H",300,.27,"Straight","#E8DCC0",9,3,"$$","East Asia","Furniture, instruments, boxes"),
("Camphor","Cinnamomum camphora","H",1100,.52,"Interlocked","#B08050",7,7,"$$","East Asia","Chests, furniture, carving"),
("Japanese Cedar","Cryptomeria japonica","S",400,.35,"Straight","#C8956C",8,6,"$$","Japan","Construction, barrels, trim"),
("Japanese Cypress","Chamaecyparis obtusa","S",520,.41,"Straight","#E8D4B0",8,7,"$$$","Japan","Temples, baths, furniture"),
("Kauri","Agathis australis","S",600,.45,"Straight","#D4B880",8,5,"$$$","New Zealand","Furniture, boats, veneer"),
("Radiata Pine","Pinus radiata","S",570,.42,"Straight","#E0C080",8,3,"$","Australasia","Construction, plywood, furniture"),
("Blackbutt","Eucalyptus pilularis","H",2100,.79,"Interlocked","#B08050",5,7,"$$$","Australia","Flooring, decking, construction"),
("Spotted Gum","Corymbia maculata","H",2200,.78,"Interlocked","#A0784C",5,8,"$$$","Australia","Flooring, decking, tools"),
("Tasmanian Oak","Eucalyptus delegatensis","H",1500,.62,"Straight","#D4A870",7,5,"$$","Australia","Furniture, flooring, joinery"),
("Huon Pine","Lagarostrobos franklinii","S",500,.42,"Straight","#DAC080",8,9,"$$$$","Australia","Boats, furniture, turning"),
("Obeche","Triplochiton scleroxylon","H",340,.30,"Interlocked","#F0E0C0",9,2,"$","Africa","Models, veneer, trim"),
("Okoume","Aucoumea klaineana","H",380,.36,"Interlocked","#D4A070",8,3,"$","Africa","Plywood, veneer, boats"),
("Greenheart","Chlorocardium rodiei","H",2900,1.00,"Interlocked","#4A6030",3,10,"$$$","South America","Marine, wharves, locks"),
("Sucupira","Bowdichia nitida","H",2790,.90,"Interlocked","#5C3820",3,9,"$$$","South America","Flooring, outdoor, furniture"),
("Garapa","Apuleia leiocarpa","H",1620,.72,"Interlocked","#DAC070",5,7,"$$","South America","Decking, siding, flooring"),
("Massaranduba","Manilkara bidentata","H",3190,.95,"Straight","#7C3C28",3,9,"$$$","South America","Decking, construction, flooring"),
("Tigerwood","Astronium graveolens","H",1850,.76,"Interlocked","#B8601A",5,7,"$$$","South America","Decking, flooring, furniture"),
("Chakte Viga","Caesalpinia platyloba","H",2250,.88,"Straight","#FF6600",5,7,"$$$","Mexico","Flooring, turning, accents"),
("Chechen","Metopium brownei","H",2250,.83,"Straight","#4A3020",5,8,"$$$","Central America","Furniture, flooring, turning"),
("Macassar Ebony","Diospyros celebica","H",3220,1.09,"Straight","#201010",3,9,"$$$$","Indonesia","Instruments, veneer, luxury"),
("Honduras Rosewood","Dalbergia stevensonii","H",2200,.80,"Straight","#6B3A28",5,8,"$$$$","Central America","Marimbas, guitars, furniture"),
("European Oak","Quercus robur","H",1120,.56,"Straight","#B8956A",7,8,"$$","Europe","Furniture, barrels, flooring"),
("European Beech","Fagus sylvatica","H",1300,.64,"Straight","#DCC0A0",6,4,"$$","Europe","Furniture, bending, toys"),
("European Ash","Fraxinus excelsior","H",1320,.60,"Straight","#D4C0A0",7,5,"$$","Europe","Tool handles, furniture, sports"),
("Scots Pine","Pinus sylvestris","S",540,.42,"Straight","#D4A060",7,4,"$","Europe","Construction, furniture, poles"),
("Norway Spruce","Picea abies","S",510,.40,"Straight","#F0DCC0",8,3,"$","Europe","Construction, instruments, paper"),
("European Larch","Larix decidua","S",830,.52,"Straight","#CC9060",6,7,"$$","Europe","Outdoor, boats, cladding"),
("Yew","Taxus baccata","S",1520,.60,"Irregular","#A06040",5,8,"$$$","Europe","Bows, furniture, veneer"),
("Boxwood","Buxus sempervirens","H",2840,.91,"Straight","#F0DCA0",4,6,"$$$","Europe","Instruments, chess, engraving"),
("European Walnut","Juglans regia","H",1010,.55,"Wavy","#4A3020",8,7,"$$$","Europe","Furniture, gunstocks, veneer"),
("English Elm","Ulmus procera","H",830,.50,"Interlocked","#A08050",6,4,"$$","Europe","Furniture, turning, coffins"),
("European Lime","Tilia europaea","H",400,.32,"Straight","#F0E0C0",10,2,"$","Europe","Carving, instruments, models"),
("European Cherry","Prunus avium","H",950,.50,"Straight","#A06040",8,5,"$$$","Europe","Furniture, instruments, turning"),
("European Sycamore","Acer pseudoplatanus","H",900,.50,"Wavy","#F0DCC0",7,3,"$$","Europe","Instruments, veneer, kitchen"),
("European Alder","Alnus glutinosa","H",590,.41,"Straight","#B08060",8,3,"$","Europe","Turning, charcoal, smoking"),
("European Birch","Betula pendula","H",1210,.57,"Straight","#F0D8B0",7,3,"$$","Europe","Plywood, furniture, veneer"),
("European Hornbeam","Carpinus betulus","H",1630,.73,"Irregular","#E8D4B0",5,5,"$$","Europe","Tools, piano parts, flooring"),
("Sweet Chestnut","Castanea sativa","H",640,.48,"Straight","#A08050",8,7,"$$","Europe","Fencing, furniture, barrels"),
("Cork Oak","Quercus suber","H",1030,.56,"Interlocked","#A08050",6,6,"$$","Mediterranean","Cork, furniture, flooring"),
("Narra","Pterocarpus dalbergioides","H",1400,.62,"Interlocked","#A06040",7,7,"$$$","Southeast Asia","Furniture, cabinetry, carving"),
("Philippine Mahogany","Shorea spp.","H",780,.45,"Interlocked","#A05040",7,5,"$$","Southeast Asia","Furniture, boats, plywood"),
("Meranti","Shorea parvifolia","H",700,.43,"Interlocked","#A05040",7,4,"$$","Southeast Asia","Plywood, furniture, windows"),
("Ramin","Gonystylus bancanus","H",1260,.52,"Straight","#E0C890",7,3,"$$","Southeast Asia","Mouldings, frames, dowels"),
("Jelutong","Dyera costulata","H",390,.36,"Straight","#F5E6D0",9,2,"$","Southeast Asia","Carving, patterns, boards"),
("Kempas","Koompassia malaccensis","H",1710,.76,"Interlocked","#A0543C",4,7,"$$","Southeast Asia","Flooring, construction, decking"),
("Keruing","Dipterocarpus spp.","H",1270,.69,"Interlocked","#9C6C48",5,6,"$$","Southeast Asia","Plywood, construction, trucks"),
("Nyatoh","Palaquium spp.","H",1020,.50,"Straight","#B07050",7,4,"$$","Southeast Asia","Furniture, mouldings, plywood"),
("Kapur","Dryobalanops spp.","H",1350,.66,"Interlocked","#9C6040",5,7,"$$","Southeast Asia","Heavy construction, flooring"),
("Indian Laurel","Terminalia tomentosa","H",1350,.68,"Interlocked","#6B4030",6,7,"$$","India","Furniture, construction, boats"),
("Sal","Shorea robusta","H",1680,.72,"Interlocked","#7C4C30",5,8,"$$","India","Construction, railway, bridges"),
("Deodar Cedar","Cedrus deodara","S",570,.44,"Straight","#C8A870",8,7,"$$","India","Construction, furniture, railway"),
("Indian Rosewood","Dalbergia sissoo","H",1660,.72,"Interlocked","#5C3020",6,8,"$$$","India","Furniture, carving, veneer"),
("Sapodilla","Manilkara zapota","H",2240,.84,"Straight","#7C4030",4,8,"$$","Central America","Heavy construction, railway"),
("Mora","Mora excelsa","H",2460,.92,"Interlocked","#7C4432",4,8,"$$","South America","Heavy construction, marine"),
("Angelim Pedra","Hymenolobium petraeum","H",1720,.69,"Interlocked","#A07050",5,7,"$$","South America","Construction, flooring, bridges"),
("Peroba Rosa","Aspidosperma polyneuron","H",1550,.71,"Straight","#C08060",6,7,"$$","Brazil","Furniture, flooring, construction"),
("Tatajuba","Bagassa guianensis","H",2300,.82,"Interlocked","#DAA520",5,8,"$$","South America","Decking, flooring, construction"),
("Amendoim","Pterogyne nitens","H",1370,.68,"Interlocked","#B88050",6,5,"$$","South America","Flooring, furniture, turning"),
("Imbuia","Phoebe porosa","H",950,.55,"Wavy","#6B4030",7,6,"$$$","Brazil","Furniture, veneer, gun stocks"),
("Freijo","Cordia goeldiana","H",690,.45,"Straight","#B08050",8,5,"$$","Brazil","Furniture, veneer, boats"),
("Cedro","Cedrela fissilis","H",600,.40,"Straight","#A07050",9,6,"$$","South America","Furniture, cigar boxes, boats"),
("Primavera","Tabebuia donnell-smithii","H",690,.42,"Wavy","#F0D890",8,4,"$$$","Central America","Furniture, veneer, plywood"),
("Gmelina","Gmelina arborea","H",570,.41,"Straight","#D4B080",8,4,"$","Southeast Asia","Furniture, plywood, carving"),
("Albizia","Albizia spp.","H",680,.45,"Interlocked","#C4A070",7,4,"$","Africa","Furniture, plywood, shade"),
("Curupay","Anadenanthera colubrina","H",3340,1.04,"Irregular","#5C2C18",3,9,"$$$","South America","Decking, outdoor, flooring"),
("Lapacho","Handroanthus lapacho","H",3400,.95,"Interlocked","#5A3A28",3,10,"$$$","South America","Decking, outdoor construction"),
("Quebracho","Schinopsis balansae","H",4570,1.12,"Interlocked","#5C2820",2,10,"$$$","South America","Fence posts, tannin"),
("Alerce","Fitzroya cupressoides","S",420,.38,"Straight","#B88060",8,9,"$$$$","South America","Shingles, boats, construction"),
("Monkey Puzzle","Araucaria araucana","S",620,.46,"Straight","#D4B880",7,5,"$$","South America","Lumber, veneer, construction"),
("Parana Pine","Araucaria angustifolia","S",780,.50,"Straight","#D4A870",7,5,"$$","South America","Interior trim, furniture"),
("Rimu","Dacrydium cupressinum","S",500,.40,"Straight","#B87850",7,4,"$$","New Zealand","Furniture, trim, flooring"),
("Totara","Podocarpus totara","S",430,.39,"Straight","#B08060",8,7,"$$","New Zealand","Fence posts, marine, carving"),
("Norfolk Island Pine","Araucaria heterophylla","S",580,.45,"Straight","#E0C890",7,3,"$$","Norfolk Island","Turning, furniture, decor"),
("Caribbean Pine","Pinus caribaea","S",750,.48,"Straight","#D4A870",7,4,"$","Caribbean","Construction, plywood"),
("Stone Pine","Pinus pinea","S",550,.45,"Straight","#D4A870",7,4,"$$","Mediterranean","Furniture, construction"),
("Cedar of Lebanon","Cedrus libani","S",660,.47,"Straight","#C8A070",7,7,"$$$","Mediterranean","Furniture, building, carving"),
("Swiss Stone Pine","Pinus cembra","S",450,.38,"Straight","#E0C090",8,4,"$$","Europe","Carving, furniture, paneling"),
("Horse Chestnut","Aesculus hippocastanum","H",450,.51,"Interlocked","#F0E0CC",8,2,"$","Europe","Turning, carving, toys"),
("Robinia","Robinia pseudoacacia","H",1700,.69,"Straight","#8B7D3C",5,10,"$$","Europe","Outdoor, playground, barrels"),
("White Willow","Salix alba","H",360,.34,"Straight","#E0D0B0",9,2,"$","Europe","Cricket bats, baskets, charcoal"),
("Poplar","Populus nigra","H",410,.35,"Straight","#E0D0B0",8,2,"$","Europe","Plywood, pallets, matches"),
("Plane Tree","Platanus x hispanica","H",770,.49,"Interlocked","#D4B890",6,3,"$$","Europe","Veneer, butcher blocks"),
("Laburnum","Laburnum anagyroides","H",1200,.58,"Straight","#6B5030",6,6,"$$$","Europe","Turning, inlays, instruments"),
("Service Tree","Sorbus domestica","H",1450,.70,"Straight","#C08060",5,6,"$$$","Europe","Tools, instruments, turning"),
("Wild Cherry","Prunus avium","H",950,.50,"Straight","#A06040",8,5,"$$$","Europe","Furniture, instruments"),
("Pear","Pyrus communis","H",1630,.69,"Straight","#C08070",6,4,"$$$","Europe","Rulers, instruments, carving"),
("Apple","Malus domestica","H",1730,.75,"Irregular","#B07060",5,5,"$$$","Europe","Turning, smoking, mallet heads"),
("Olive Ash","Fraxinus excelsior","H",1320,.60,"Wavy","#B8956A",7,5,"$$","Europe","Furniture, veneer, sports"),
("London Plane","Platanus x acerifolia","H",770,.49,"Interlocked","#D4B890",6,3,"$$","Europe","Veneer, furniture"),
("Wych Elm","Ulmus glabra","H",830,.50,"Interlocked","#A08050",6,4,"$$","Europe","Boats, chairs, coffins"),
("Field Maple","Acer campestre","H",1100,.59,"Wavy","#E0C8A0",7,4,"$$","Europe","Turning, musical instruments"),
("Black Poplar","Populus nigra","H",410,.35,"Straight","#E0D0B0",8,2,"$","Europe","Plywood, crates, matches"),
("Tamarack","Larix laricina","S",590,.48,"Straight","#CC9060",6,5,"$$","North America","Posts, railroad ties, boats"),
("Sitka Spruce","Picea sitchensis","S",510,.37,"Straight","#F0DCC0",8,3,"$","North America","Aircraft, instruments, masts"),
("Ponderosa Pine","Pinus ponderosa","S",460,.38,"Straight","#E0B870",8,3,"$","North America","Construction, millwork, trim"),
("Sugar Pine","Pinus lambertiana","S",380,.34,"Straight","#F0D8C0",9,3,"$","North America","Patterns, millwork, doors"),
("Jack Pine","Pinus banksiana","S",570,.43,"Straight","#D4A060",7,3,"$","North America","Pulp, construction, poles"),
("Lodgepole Pine","Pinus contorta","S",480,.38,"Straight","#D4A870",7,3,"$","North America","Construction, railroad ties"),
("White Spruce","Picea glauca","S",480,.37,"Straight","#F0E0CC",8,3,"$","North America","Construction, pulp, instruments"),
("Red Pine","Pinus resinosa","S",560,.41,"Straight","#D4A060",7,4,"$","North America","Construction, poles, pilings"),
("Port Orford Cedar","Chamaecyparis lawsoniana","S",580,.43,"Straight","#E0C890",8,8,"$$$","North America","Boats, arrows, instruments"),
("Alaska Yellow Cedar","Callitropsis nootkatensis","S",580,.44,"Straight","#E0D0A0",8,9,"$$$","North America","Boats, carvings, outdoor"),
("Atlantic White Cedar","Chamaecyparis thyoides","S",350,.32,"Straight","#D4B080",9,8,"$$","North America","Boats, shingles, decoys"),
("Incense Cedar","Calocedrus decurrens","S",470,.35,"Straight","#C8A070",9,7,"$$","North America","Pencils, closets, decking"),
("Noble Fir","Abies procera","S",430,.37,"Straight","#E0C8A0",8,3,"$","North America","Construction, interior trim"),
("White Fir","Abies concolor","S",430,.37,"Straight","#F0E0CC",8,3,"$","North America","Construction, crates, pulp"),
("Bigleaf Maple","Acer macrophyllum","H",850,.48,"Wavy","#E0C890",8,4,"$$","North America","Instruments, veneer, furniture"),
("Oregon Myrtle","Umbellularia californica","H",1270,.51,"Wavy","#9C8040",6,5,"$$$","North America","Turning, furniture, veneer"),
("Hackberry","Celtis occidentalis","H",880,.49,"Straight","#D4B890",7,3,"$","North America","Furniture, crates, turning"),
("Honeylocust","Gleditsia triacanthos","H",1580,.60,"Interlocked","#A07040",5,7,"$$","North America","Fence posts, pallets, furniture"),
("Kentucky Coffeetree","Gymnocladus dioicus","H",1390,.57,"Straight","#A07040",6,7,"$$","North America","Fence posts, furniture, cabinetry"),
("Sassafras","Sassafras albidum","H",630,.42,"Straight","#B09060",8,6,"$$","North America","Boats, furniture, fence posts"),
("Catalpa","Catalpa speciosa","H",530,.38,"Straight","#C4A870",8,7,"$","North America","Fence posts, furniture, boats"),
("Chinkapin","Castanopsis chrysophylla","H",820,.46,"Straight","#B09060",7,5,"$$","North America","Furniture, flooring, veneer"),
("Ohio Buckeye","Aesculus glabra","H",350,.33,"Straight","#F0E0CC",9,2,"$","North America","Carving, artificial limbs"),
("Sweetgum","Liquidambar styraciflua","H",850,.46,"Interlocked","#B08060",6,3,"$","North America","Veneer, plywood, furniture"),
("Tupelo","Nyssa sylvatica","H",810,.46,"Interlocked","#C4A870",6,3,"$","North America","Carving, crates, turning"),
("White Cedar","Thuja occidentalis","S",320,.29,"Straight","#D4B880",9,7,"$","North America","Shingles, posts, canoes"),
("Chestnut","Castanea dentata","H",540,.40,"Straight","#A08050",8,8,"$$$","North America","Furniture, fencing, reclaimed"),
("Tanoak","Notholithocarpus densiflorus","H",1420,.58,"Straight","#B08060",5,4,"$","North America","Firewood, tanbark, flooring"),
("Water Oak","Quercus nigra","H",1190,.56,"Straight","#B8956A",6,4,"$","North America","Pallets, crates, firewood"),
("Live Oak","Quercus virginiana","H",2680,.87,"Interlocked","#8B7340",3,9,"$$$","North America","Ship building, furniture"),
("Swamp White Oak","Quercus bicolor","H",1360,.64,"Straight","#C4A35A",7,8,"$$","North America","Barrels, furniture, flooring"),
("Chestnut Oak","Quercus montana","H",1300,.60,"Straight","#B8956A",7,6,"$$","North America","Fencing, railroad ties, flooring"),
("Overcup Oak","Quercus lyrata","H",1190,.56,"Straight","#B8956A",7,5,"$$","North America","Furniture, barrels, flooring"),
("Pin Oak","Quercus palustris","H",1500,.63,"Straight","#B5651D",6,4,"$","North America","Firewood, pallets, construction"),
("Post Oak","Quercus stellata","H",1350,.60,"Straight","#B8956A",6,8,"$$","North America","Fence posts, construction"),
("Bur Oak","Quercus macrocarpa","H",1360,.64,"Straight","#C4A35A",7,8,"$$","North America","Furniture, barrels, flooring"),
("Chinquapin Oak","Quercus muehlenbergii","H",1350,.60,"Straight","#B8956A",7,7,"$$","North America","Fencing, construction, flooring"),
("Scarlet Oak","Quercus coccinea","H",1300,.60,"Straight","#B5651D",6,4,"$","North America","Firewood, construction"),
("Willow Oak","Quercus phellos","H",1210,.56,"Straight","#B8956A",7,4,"$","North America","Pallets, construction"),
("Laurel Oak","Quercus laurifolia","H",1200,.56,"Straight","#B8956A",7,4,"$","North America","Pallets, construction"),
("Northern Red Oak","Quercus rubra","H",1290,.63,"Straight","#B5651D",7,6,"$$","North America","Furniture, flooring, veneer"),
("Southern Red Oak","Quercus falcata","H",1060,.52,"Straight","#B5651D",6,4,"$","North America","Construction, pallets"),
("Black Oak","Quercus velutina","H",1210,.56,"Straight","#B5651D",6,4,"$","North America","Construction, firewood"),
("Cherrybark Oak","Quercus pagoda","H",1280,.60,"Straight","#B5651D",7,5,"$$","North America","Furniture, flooring, veneer"),
]

FREE_COUNT = 50

def make_species(i, t):
    name, sci, cat, janka, dens, grain, chex, work, dur, price, region, uses = t
    category = "Hardwood" if cat == "H" else "Softwood"
    return {
        "name": name,
        "scientificName": sci,
        "speciesDescription": f"{name} ({sci}) is a {category.lower()} native to {region}.",
        "category": category,
        "hardness": janka,
        "density": dens,
        "grainPattern": grain,
        "colorHex": chex,
        "uses": uses,
        "pricing": price,
        "imageURL": "",
        "region": region,
        "workability": work,
        "durability": dur,
        "isFreeSpecies": i < FREE_COUNT,
        "workingTips": f"{'Easy' if work >= 7 else 'Moderate' if work >= 4 else 'Difficult'} to work with hand and machine tools.",
        "shrinkageRadial": round(dens * 5.5, 1),
        "shrinkageTangential": round(dens * 9.0, 1),
        "sustainability": "Common" if price in ("$", "$$") else "Moderate" if price == "$$$" else "Limited",
        "confusedWith": "",
        "heroImages": [],
        "databaseVersion": 1
    }

species = [make_species(i, t) for i, t in enumerate(DATA)]
out = {"version": 1, "species": species}

import pathlib, sys
out_dir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(".")
out_path = out_dir / "WoodIdentifier" / "Resources" / "wood_species.json"
out_path.parent.mkdir(parents=True, exist_ok=True)
with open(out_path, "w") as f:
    json.dump(out, f, indent=2)
print(f"Generated {len(species)} species to {out_path}")
